spring:
  cloud:
    stream:
      rabbit:
        bindings:
          downloader-in:
            consumer:
              maxPriority: 10
      bindings:
        main-in:
          destination: main
          binder: rabbit
          contentType: application/json
          group: main
        main-out:
          destination: downloader
          binder: rabbit
          contentType: application/json
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: rabbit
                port: 5672
                username: crawler
                password: crawler@rabbit123
  rabbitmq:
    host: rabbit
    port: 5672
    username: crawler
    password: crawler@rabbit123
server:
  servlet:
    context-path: /api
  port: 9090